name: "Lily58 Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/lily58.yml

jobs:
  lily58-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: lily58
          keymap: default
          output-dir: lily58
      - uses: sylvanld/action-storage@v1
        with:
          src: lily58
          dst: ./
          storage-branch: main

  lily58-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: lily58
          keymap: via
          output-dir: lily58
      - uses: sylvanld/action-storage@v1
        with:
          src: lily58
          dst: ./
          storage-branch: main

  lily58-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: lily58
          keymap: default
          controller: helios
          output-dir: lily58
      - uses: sylvanld/action-storage@v1
        with:
          src: lily58
          dst: ./
          storage-branch: main

  lily58-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: lily58
          keymap: via
          controller: helios
          output-dir: lily58
      - uses: sylvanld/action-storage@v1
        with:
          src: lily58
          dst: ./
          storage-branch: main