name: "Sofle Choc Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/sofle_choc.yml

jobs:
  sofle_choc-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: sofle_choc
          keymap: default
          output-dir: sofle_choc
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_choc
          dst: ./
          storage-branch: main

  sofle_choc-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: sofle_choc
          keymap: via
          output-dir: sofle_choc
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_choc
          dst: ./
          storage-branch: main

  sofle_choc-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: sofle_choc
          keymap: default
          controller: helios
          output-dir: sofle_choc
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_choc
          dst: ./
          storage-branch: main

  sofle_choc-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: sofle_choc
          keymap: via
          controller: helios
          output-dir: sofle_choc
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_choc
          dst: ./
          storage-branch: main