name: "ArtPad Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/artpad.yml
    - artpad/**

jobs:

  artpad-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@vial-qmk
        with:
          keyboard: artpad
          keymap: vial
          controller: helios
          local-keyboard-path: artpad
          output-dir: artpad
      - uses: sylvanld/action-storage@v1
        with:
          src: cantor
          dst: ./
          storage-branch: main