name: "ArtPad Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/artpad.yml
    - artpad/**

jobs:

  artpad-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v2-vial
        with:
          keyboard: artpad
          keymap: vial
          controller: helios
          local-keyboard-path: artpad
      - uses: StirlingLabs/BranchStorageAction@main
        with:
          src: qmk-output/**
          dst: artpad
          storage-branch: firmware
          prune: true