name: "Basketweave Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/milk.yml

jobs:

  basketweave-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: basketweave
          keymap: default
          output-dir: basketweave
      - uses: sylvanld/action-storage@v1
        with:
          src: basketweave
          dst: ./
          storage-branch: main