name: "Cantor Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/cantor.yml

jobs:
  cantor-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: cantor
          keymap: default
          output-dir: cantor
      - uses: sylvanld/action-storage@v1
        with:
          src: cantor
          dst: ./
          storage-branch: main