name: "Contra Firmware"

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/contra.yml

jobs:
  contra-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: contra
          keymap: default
          output-dir: contra-default
      - uses: sylvanld/action-storage@v1
        with:
          src: contra-default
          dst: ./
          storage-branch: main

  contra-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: contra
          keymap: via
          output-dir: contra-via
      - uses: sylvanld/action-storage@v1
        with:
          src: contra-via
          dst: ./
          storage-branch: main