name: "Contra Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/contra.yml

jobs:
  contra-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: contra
          keymap: default
          controller: helios
          output-dir: contra
      - uses: sylvanld/action-storage@v1
        with:
          src: contra
          dst: ./
          storage-branch: main

  contra-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: contra
          keymap: via
          controller: helios
          output-dir: contra
          local-keymap-path: contra/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: contra
          dst: ./
          storage-branch: main

  contra-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: contra
          keymap: vial
          controller: helios
          output-dir: contra
      - uses: sylvanld/action-storage@v1
        with:
          src: contra
          dst: ./
          storage-branch: main

  contra-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: contra
          keymap: default
          controller: svlinky
          output-dir: contra
      - uses: sylvanld/action-storage@v1
        with:
          src: contra
          dst: ./
          storage-branch: main

  contra-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: contra
          keymap: via
          controller: svlinky
          output-dir: contra
          local-keymap-path: contra/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: contra
          dst: ./
          storage-branch: main

  contra-vial-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: contra
          keymap: vial
          controller: svlinky
          output-dir: contra
      - uses: sylvanld/action-storage@v1
        with:
          src: contra
          dst: ./
          storage-branch: main