name: "Corne Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/corne.yml
    - corne/**

jobs:
  corne-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: crkbd/rev1
          keymap: default
          controller: helios
          output-dir: corne
      - uses: sylvanld/action-storage@v1
        with:
          src: corne
          dst: ./
          storage-branch: main

  corne-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: crkbd/rev1
          keymap: via
          controller: helios
          output-dir: corne
          local-keymap-path: corne/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: corne
          dst: ./
          storage-branch: main

  corne-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: crkbd/rev1
          keymap: vial
          controller: helios
          output-dir: corne
      - uses: sylvanld/action-storage@v1
        with:
          src: corne
          dst: ./
          storage-branch: main

  corne-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: crkbd/rev1
          keymap: default
          controller: svlinky
          output-dir: corne
      - uses: sylvanld/action-storage@v1
        with:
          src: corne
          dst: ./
          storage-branch: main

  corne-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: crkbd/rev1
          keymap: via
          controller: svlinky
          output-dir: corne
          local-keymap-path: corne/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: corne
          dst: ./
          storage-branch: main

  corne-vial-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: crkbd/rev1
          keymap: vial
          controller: svlinky
          output-dir: corne
      - uses: sylvanld/action-storage@v1
        with:
          src: corne
          dst: ./
          storage-branch: main