name: "Discipad Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/discipad.yml
    - discipad/**

jobs:
  discipad-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: coseyfannitutti/discipad
          keymap: default
          output-dir: discipad
      - uses: sylvanld/action-storage@v1
        with:
          src: discipad
          dst: ./
          storage-branch: main

  discipad-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: coseyfannitutti/discipad
          keymap: via
          output-dir: discipad
          local-keymap-path: discipad/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: discipad
          dst: ./
          storage-branch: main