name: "Draculad Firmware"

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/draculad.yml

jobs:
  draculad-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: draculad
          keymap: default
          output-dir: draculad
      - uses: sylvanld/action-storage@v1
        with:
          src: draculad
          dst: ./
          storage-branch: main

  draculad-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: draculad
          keymap: via
          output-dir: draculad
          local-keymap-path: draculad/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: draculad
          dst: ./
          storage-branch: main