name: "Draculad Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/draculad.yml
    - draculad/**

jobs:
  draculad-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: draculad
          keymap: default
          controller: helios
          output-dir: draculad
      - uses: sylvanld/action-storage@v1
        with:
          src: draculad
          dst: ./
          storage-branch: main

  draculad-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: draculad
          keymap: via
          controller: helios
          output-dir: draculad
          local-keymap-path: draculad/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: draculad
          dst: ./
          storage-branch: main
  
  draculad-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: draculad
          keymap: default
          controller: svlinky
          output-dir: draculad
      - uses: sylvanld/action-storage@v1
        with:
          src: draculad
          dst: ./
          storage-branch: main

  draculad-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: draculad
          keymap: via
          controller: svlinky
          output-dir: draculad
          local-keymap-path: draculad/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: draculad
          dst: ./
          storage-branch: main