name: "Dumbpad OLED Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/dumbpad_oled.yml
    - dumbpad_oled/**

jobs:
  dumbpad_oled-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: dumbpad/v1x_oled
          keymap: default
          controller: helios
          output-dir: dumbpad_oled
      - uses: sylvanld/action-storage@v1
        with:
          src: dumbpad_oled
          dst: ./
          storage-branch: main

  dumbpad_oled-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: dumbpad/v1x_oled
          keymap: via
          controller: helios
          output-dir: dumbpad_oled
          local-keymap-path: dumbpad_oled/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: dumbpad_oled
          dst: ./
          storage-branch: main

  dumbpad_oled-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: dumbpad/v1x_oled
          keymap: default
          controller: svlinky
          output-dir: dumbpad_oled
      - uses: sylvanld/action-storage@v1
        with:
          src: dumbpad_oled
          dst: ./
          storage-branch: main

  dumbpad_oled-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: dumbpad/v1x_oled
          keymap: via
          controller: svlinky
          output-dir: dumbpad_oled
          local-keymap-path: dumbpad_oled/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: dumbpad_oled
          dst: ./
          storage-branch: main