name: "Ergodash Mini Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/ergodash_mini.yml
    - ergodash_mini/keymaps/**

jobs:
  ergodash_mini-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: omkbd/ergodash/mini
          keymap: default
          output-dir: ergodash_mini
      - uses: sylvanld/action-storage@v1
        with:
          src: ergodash_mini
          dst: ./
          storage-branch: main

  ergodash_mini-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: omkbd/ergodash/mini
          keymap: via
          output-dir: ergodash_mini
          local-keymap-path: ergodash_mini/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: ergodash_mini
          dst: ./
          storage-branch: main

  ergodash_mini-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: omkbd/ergodash/mini
          keymap: default
          controller: helios
          output-dir: ergodash_mini
      - uses: sylvanld/action-storage@v1
        with:
          src: ergodash_mini
          dst: ./
          storage-branch: main

  ergodash_mini-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: omkbd/ergodash/mini
          keymap: via
          controller: helios
          output-dir: ergodash_mini
          local-keymap-path: ergodash_mini/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: ergodash_mini
          dst: ./
          storage-branch: main