name: "Eternal Keypad Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/eternal_keypad.yml
    - eternal_keypad/**

jobs:
  eternal_keypad-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: eternal_keypad
          keymap: default
          controller: helios
          output-dir: eternal_keypad
      - uses: sylvanld/action-storage@v1
        with:
          src: eternal_keypad
          dst: ./
          storage-branch: main

  eternal_keypad-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: eternal_keypad
          keymap: via
          controller: helios
          output-dir: eternal_keypad
          local-keymap-path: eternal_keypad/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: eternal_keypad
          dst: ./
          storage-branch: main

  eternal_keypad-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: eternal_keypad
          keymap: default
          controller: svlinky
          output-dir: eternal_keypad
      - uses: sylvanld/action-storage@v1
        with:
          src: eternal_keypad
          dst: ./
          storage-branch: main

  eternal_keypad-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: eternal_keypad
          keymap: via
          controller: svlinky
          output-dir: eternal_keypad
          local-keymap-path: eternal_keypad/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: eternal_keypad
          dst: ./
          storage-branch: main