name: "QMK Firmware Files"

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  cantor-default:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: d3adb5/build-qmk-fw@v1
      with:
        keyboard: cantor
        keymap: default
        output-dir: cantor-default
    - uses: sylvanld/action-storage@v1
      with:
        src: cantor-default
        dst: ./
        storage-branch: main

  contra-default:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: d3adb5/build-qmk-fw@v1
      with:
        keyboard: contra
        keymap: default
        output-dir: contra-default
    - uses: sylvanld/action-storage@v1
      with:
        src: contra-default
        dst: ./
        storage-branch: main

  contra-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: contra
          keymap: via
          output-dir: contra-via
      - uses: sylvanld/action-storage@v1
        with:
          src: contra-via
          dst: ./
          storage-branch: main

  corne-default:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: d3adb5/build-qmk-fw@v1
      with:
        keyboard: crkbd/rev1
        keymap: default
        output-dir: corne-default
    - uses: sylvanld/action-storage@v1
      with:
        src: corne-default
        dst: ./
        storage-branch: main

  corne-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: crkbd/rev1
          keymap: via
          output-dir: corne-via
      - uses: sylvanld/action-storage@v1
        with:
          src: corne-via
          dst: ./
          storage-branch: main

  corne-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: crkbd/rev1
          keymap: default
          controller: helios
          output-dir: corne-default-helios

      - uses: sylvanld/action-storage@v1
        with:
          src: corne-default-helios
          dst: ./
          storage-branch: main

  corne-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: crkbd/rev1
          keymap: via
          controller: helios
          output-dir: corne-via-helios

      - uses: sylvanld/action-storage@v1
        with:
          src: corne-via-helios
          dst: ./
          storage-branch: main
