name: "KEEBD Tree Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/keebd_tree.yml
    - keebd_tree/**

jobs:

  keebd-tree-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: keebd_tree
          keymap: default
          local-keyboard-path: keebd_tree
          output-dir: keebd_tree
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_tree
          dst: ./
          storage-branch: main

  keebd-tree-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: keebd_tree
          keymap: via
          local-keyboard-path: keebd_tree
          output-dir: keebd_tree
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_tree
          dst: ./
          storage-branch: main

  keebd-tree-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: keebd_tree
          keymap: default
          controller: helios
          local-keyboard-path: keebd_tree
          output-dir: keebd_tree
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_tree
          dst: ./
          storage-branch: main

  keebd-tree-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: keebd_tree
          keymap: via
          controller: helios
          local-keyboard-path: keebd_tree
          output-dir: keebd_tree
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_tree
          dst: ./
          storage-branch: main