name: "KEEBD Corne LP Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/keebd_corne_lp.yml
    - keebd_corne_lp/**

jobs:
  keebd-corne-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: keebd_corne_lp
          keymap: default
          controller: helios
          local-keyboard-path: keebd_corne_lp
          output-dir: keebd_corne_lp
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_corne_lp
          dst: ./
          storage-branch: main

  keebd-corne-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: keebd_corne_lp
          keymap: via
          controller: helios
          local-keyboard-path: keebd_corne_lp
          output-dir: keebd_corne_lp
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_corne_lp
          dst: ./
          storage-branch: main

  keebd-corne-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: keebd_corne_lp
          keymap: vial
          controller: helios
          local-keyboard-path: keebd_corne_lp
          output-dir: keebd_corne_lp
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_corne_lp
          dst: ./
          storage-branch: main

  keebd-corne-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: keebd_corne_lp
          keymap: default
          controller: svlinky
          local-keyboard-path: keebd_corne_lp
          output-dir: keebd_corne_lp
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_corne_lp
          dst: ./
          storage-branch: main

  keebd-corne-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: keebd_corne_lp
          keymap: via
          controller: svlinky
          local-keyboard-path: keebd_corne_lp
          output-dir: keebd_corne_lp
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_corne_lp
          dst: ./
          storage-branch: main

  keebd-corne-vial-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: keebd_corne_lp
          keymap: vial
          controller: svlinky
          local-keyboard-path: keebd_corne_lp
          output-dir: keebd_corne_lp
      - uses: sylvanld/action-storage@v1
        with:
          src: keebd_corne_lp
          dst: ./
          storage-branch: main