name: "Narfpad Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/narfpad.yml
    - narfpad/**

jobs:
  narfpad-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: narfpad
          controller: helios
          local-keyboard-path: narfpad
          output-dir: narfpad
      - uses: sylvanld/action-storage@v1
        with:
          src: narfpad
          dst: ./
          storage-branch: main

  narfpad-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: narfpad
          keymap: via
          controller: helios
          local-keyboard-path: narfpad
          output-dir: narfpad
      - uses: sylvanld/action-storage@v1
        with:
          src: narfpad
          dst: ./
          storage-branch: main

  narfpad-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: narfpad
          controller: svlinky
          local-keyboard-path: narfpad
          output-dir: narfpad
      - uses: sylvanld/action-storage@v1
        with:
          src: narfpad
          dst: ./
          storage-branch: main

  narfpad-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: narfpad
          keymap: via
          controller: svlinky
          local-keyboard-path: narfpad
          output-dir: narfpad
      - uses: sylvanld/action-storage@v1
        with:
          src: narfpad
          dst: ./
          storage-branch: main