name: "Reviung 5 Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/reviung5.yml
    - reviung5/**

jobs:
  reviung5-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung5
          keymap: default
          controller: helios
          output-dir: reviung5
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung5
          dst: ./
          storage-branch: main

  reviung5-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung5
          keymap: via
          controller: helios
          local-keymap-path: reviung5/keymaps/via
          output-dir: reviung5
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung5
          dst: ./
          storage-branch: main

  reviung5-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: reviung/reviung5
          keymap: vial
          controller: helios
          output-dir: reviung5
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung5
          dst: ./
          storage-branch: main

  reviung5-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung5
          keymap: default
          controller: svlinky
          output-dir: reviung5
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung5
          dst: ./
          storage-branch: main

  reviung5-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung5
          keymap: via
          controller: svlinky
          local-keymap-path: reviung5/keymaps/via
          output-dir: reviung5
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung5
          dst: ./
          storage-branch: main

  reviung5-vial-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: reviung/reviung5
          keymap: vial
          controller: svlinky
          output-dir: reviung5
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung5
          dst: ./
          storage-branch: main