name: "Reviung 39 Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/reviung39.yml
    - reviung39/**

jobs:
  reviung39-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung39
          keymap: default
          controller: helios
          output-dir: reviung39
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung39
          dst: ./
          storage-branch: main

  reviung39-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung39
          keymap: via
          controller: helios
          local-keymap-path: reviung39/keymaps/via
          output-dir: reviung39
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung39
          dst: ./
          storage-branch: main

  reviung39-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: reviung/reviung39
          keymap: vial
          controller: helios
          output-dir: reviung39
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung39
          dst: ./
          storage-branch: main

  reviung39-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung39
          keymap: default
          controller: svlinky
          output-dir: reviung39
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung39
          dst: ./
          storage-branch: main

  reviung39-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung39
          keymap: via
          controller: svlinky
          local-keymap-path: reviung39/keymaps/via
          output-dir: reviung39
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung39
          dst: ./
          storage-branch: main

  reviung39-vial-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: reviung/reviung39
          keymap: vial
          controller: svlinky
          output-dir: reviung39
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung39
          dst: ./
          storage-branch: main