name: "Reviung 5 Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/reviung5.yml

jobs:

  reviung5-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: reviung/reviung5
          keymap: default
          output-dir: reviung5
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung5
          dst: ./
          storage-branch: main

  reviung5-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@vial-qmk
        with:
          keyboard: reviung/reviung5
          keymap: vial
          controller: helios
          output-dir: reviung5
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung5
          dst: ./
          storage-branch: main