name: "Reviung 39 Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/reviung39.yml

jobs:

  reviung39-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: reviung/reviung39
          keymap: default
          output-dir: reviung39
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung39
          dst: ./
          storage-branch: main

  reviung39-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@vial-qmk
        with:
          keyboard: reviung/reviung39
          keymap: vial
          controller: helios
          output-dir: reviung39
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung39
          dst: ./
          storage-branch: main