name: "Reviung 41 Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/reviung41.yml
    - reviung41/**

jobs:
  reviung41-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung41
          keymap: default
          controller: helios
          output-dir: reviung41
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung41
          dst: ./
          storage-branch: main

  reviung41-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung41
          keymap: via
          controller: helios
          local-keymap-path: reviung41/keymaps/via
          output-dir: reviung41
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung41
          dst: ./
          storage-branch: main

  reviung41-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: reviung/reviung41
          keymap: vial
          controller: helios
          output-dir: reviung41
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung41
          dst: ./
          storage-branch: main

  reviung41-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung41
          keymap: default
          controller: svlinky
          output-dir: reviung41
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung41
          dst: ./
          storage-branch: main

  reviung41-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: reviung/reviung41
          keymap: via
          controller: svlinky
          local-keymap-path: reviung41/keymaps/via
          output-dir: reviung41
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung41
          dst: ./
          storage-branch: main

  reviung41-vial-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@vial-qmk
        with:
          keyboard: reviung/reviung41
          keymap: vial
          controller: svlinky
          output-dir: reviung41
      - uses: sylvanld/action-storage@v1
        with:
          src: reviung41
          dst: ./
          storage-branch: main