name: "Rhymestone Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/rhymestone.yml
    - rhymestone/**

jobs:
  rhymestone-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: marksard/rhymestone
          keymap: default
          controller: helios
          output-dir: rhymestone
      - uses: sylvanld/action-storage@v1
        with:
          src: rhymestone
          dst: ./
          storage-branch: main

  rhymestone-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: marksard/rhymestone
          keymap: via
          controller: helios
          local-keymap-path: rhymestone/keymaps/via
          output-dir: rhymestone
      - uses: sylvanld/action-storage@v1
        with:
          src: rhymestone
          dst: ./
          storage-branch: main

  rhymestone-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: marksard/rhymestone
          keymap: default
          controller: svlinky
          output-dir: rhymestone
      - uses: sylvanld/action-storage@v1
        with:
          src: rhymestone
          dst: ./
          storage-branch: main

  rhymestone-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: marksard/rhymestone
          keymap: via
          controller: svlinky
          local-keymap-path: rhymestone/keymaps/via
          output-dir: rhymestone
      - uses: sylvanld/action-storage@v1
        with:
          src: rhymestone
          dst: ./
          storage-branch: main