name: "Rhymestone Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/rhymestone.yml
    - rhymestone/keymaps/**

jobs:
  rhymestone-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: marksard/rhymestone
          keymap: default
          output-dir: rhymestone
      - uses: sylvanld/action-storage@v1
        with:
          src: rhymestone
          dst: ./
          storage-branch: main

  rhymestone-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: marksard/rhymestone
          keymap: default
          controller: helios
          output-dir: rhymestone
      - uses: sylvanld/action-storage@v1
        with:
          src: rhymestone
          dst: ./
          storage-branch: main