name: "Satpad Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/satpad.yml
    - satpad/**

jobs:
  satpad-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: satpad
          keymap: default
          controller: helios
          output-dir: satpad
          local-keyboard-path: satpad
      - uses: sylvanld/action-storage@v1
        with:
          src: satpad
          dst: ./
          storage-branch: main

  satpad-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: satpad
          keymap: via
          controller: helios
          output-dir: satpad
          local-keyboard-path: satpad
      - uses: sylvanld/action-storage@v1
        with:
          src: satpad
          dst: ./
          storage-branch: main

  satpad-default-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: satpad
          keymap: default
          controller: svlinky
          output-dir: satpad
          local-keyboard-path: satpad
      - uses: sylvanld/action-storage@v1
        with:
          src: satpad
          dst: ./
          storage-branch: main

  satpad-via-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: keebd/build-qmk-fw@main
        with:
          keyboard: satpad
          keymap: via
          controller: svlinky
          output-dir: satpad
          local-keyboard-path: satpad
      - uses: sylvanld/action-storage@v1
        with:
          src: satpad
          dst: ./
          storage-branch: main