name: "Sofle Svlinky Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/sofle_svlinky.yml
    - sofle_svlinky/**

jobs:

    sofle-vial:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - uses: medoix/build-qmk-fw@vial-qmk
          with:
            keyboard: sofle_svlinky
            keymap: vial
            output-dir: sofle_svlinky
            local-keyboard-path: sofle_svlinky
        - uses: sylvanld/action-storage@v1
          with:
            src: sofle_svlinky
            dst: ./
            storage-branch: main