name: "Sofle RGB Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/sofle_rgb.yml
    - sofle_rgb/keymaps/**

jobs:
  sofle_rgb-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: sofle/rev1
          keymap: default
          output-dir: sofle_rgb
          local-keymap-path: sofle_rgb/keymaps/default
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_rgb
          dst: ./
          storage-branch: main

  sofle_rgb-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: sofle/rev1
          keymap: via
          output-dir: sofle_rgb
          local-keymap-path: sofle_rgb/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_rgb
          dst: ./
          storage-branch: main

  sofle_rgb-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: sofle/rev1
          keymap: default
          controller: helios
          output-dir: sofle_rgb
          local-keymap-path: sofle_rgb/keymaps/default
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_rgb
          dst: ./
          storage-branch: main

  sofle_rgb-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: sofle/rev1
          keymap: via
          controller: helios
          output-dir: sofle_rgb
          local-keymap-path: sofle_rgb/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_rgb
          dst: ./
          storage-branch: main

  sofle_rgb-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@vial-qmk
        with:
          keyboard: sofle/rev1
          keymap: vial
          controller: helios
          output-dir: sofle_rgb
          local-keymap-path: sofle_rgb/keymaps/vial
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_rgb
          dst: ./
          storage-branch: main

  sofle_rgb-vial-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@vial-qmk
        with:
          keyboard: sofle/rev1
          keymap: vial_svlinky
          controller: helios
          output-dir: sofle_rgb
          local-keymap-path: sofle_rgb/keymaps/vial_svlinky
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle_rgb
          dst: ./
          storage-branch: main