name: "Sofle Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/sofle.yml
    - sofle/**

jobs:

  sofle-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: sofle
          keymap: rgb_default
          controller: helios
          output-dir: sofle
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle
          dst: ./
          storage-branch: main

  sofle-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@vial-qmk
        with:
          keyboard: sofle
          keymap: vial
          controller: helios
          output-dir: sofle
          local-keymap-path: sofle/keymaps/vial
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle
          dst: ./
          storage-branch: main

  sofle-vial-svlinky:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@vial-qmk
        with:
          keyboard: sofle
          keymap: svlinky
          controller: elite_pi
          output-dir: sofle
          local-keymap-path: sofle/keymaps/svlinky
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle
          dst: ./
          storage-branch: main