name: "Sofle Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/sofle.yml
    - sofle/**

jobs:
  sofle-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: sofle
          keymap: default
          output-dir: sofle
          local-keymap-path: sofle/keymaps/default
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle
          dst: ./
          storage-branch: main

  sofle-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: sofle
          keymap: via
          output-dir: sofle
          local-keymap-path: sofle/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle
          dst: ./
          storage-branch: main

  sofle-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: sofle
          keymap: default
          controller: helios
          output-dir: sofle
          local-keymap-path: sofle/keymaps/default
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle
          dst: ./
          storage-branch: main

  sofle-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@main
        with:
          keyboard: sofle
          keymap: via
          controller: helios
          output-dir: sofle
          local-keymap-path: sofle/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle
          dst: ./
          storage-branch: main

  sofle-vial-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@vial-qmk
        with:
          keyboard: sofle
          keymap: vial
          controller: helios
          output-dir: sofle
          local-keymap-path: sofle/keymaps/vial
      - uses: sylvanld/action-storage@v1
        with:
          src: sofle
          dst: ./
          storage-branch: main