name: "Treadstone48 Firmware"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - .github/workflows/treadstone48.yml
    - treadstone48/keymaps/**

jobs:
  treadstone48-default:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: treadstone48/rev1
          keymap: default
          output-dir: treadstone48
      - uses: sylvanld/action-storage@v1
        with:
          src: treadstone48
          dst: ./
          storage-branch: main

  treadstone48-via:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: treadstone48/rev1
          keymap: via
          output-dir: treadstone48
          local-keymap-path: treadstone48/rev1/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: treadstone48
          dst: ./
          storage-branch: main

  treadstone48-default-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: treadstone48/rev1
          keymap: default
          controller: helios
          output-dir: treadstone48
      - uses: sylvanld/action-storage@v1
        with:
          src: treadstone48
          dst: ./
          storage-branch: main

  treadstone48-via-helios:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: medoix/build-qmk-fw@v1
        with:
          keyboard: treadstone48/rev1
          keymap: via
          controller: helios
          output-dir: treadstone48
          local-keymap-path: treadstone48/rev1/keymaps/via
      - uses: sylvanld/action-storage@v1
        with:
          src: treadstone48
          dst: ./
          storage-branch: main